version: "3.7"
services:

  kingfisher:
    build: ./
    image: kingfisher
    container_name: kingfisher
    volumes:
      - type: bind
        source: ./kingfisher
        target: /workspace/kingfisher
    depends_on:
      - db
  db:
    image: postgres:11
    restart: unless-stopped
    container_name: kingfisherdb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    #data persistance
    #not the way i like but that doesnt wok with postgress only with mysql
    # https://stackoverflow.com/a/40333074/1297666
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    secrets:
      - postgres-passwd
      - postgres-user

  #https://medium.com/@etiennerouzeaud/play-databases-with-adminer-and-docker-53dc7789f35f
  #that should help with using adminer
  adminer:
    image: adminer
    container_name: kingfisheradminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
    name: kingfisher-data

secrets:
  postgres-passwd:
    file: ./docker/secrets/postgres-passwd
  postgres-user:
    file: ./docker/secrets/postgres-user
