version: "3.7"
services:

  kingfisher:
    build: ./
    image: kingfisher
    depends_on:
      - db

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    secrets:
      - postgres-passwd
      - postgres-user

  #https://medium.com/@etiennerouzeaud/play-databases-with-adminer-and-docker-53dc7789f35f
  #that should help with using adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db


secrets:
  postgres-passwd:
    file: ./config/docker_secrets/postgres-passwd
  postgres-user:
    file: ./config/docker_secrets/postgres-user
